name: mcarto2021
channels:
  - conda-forge
  - defaults
dependencies:
  - cartopy
  - chardet
  - colorama
  - geos
  - importlib-metadata
  - ipykernel
  - ipython
  - ipython_genutils
  - jedi
  - jinja2
  - jpeg
  - json5
  - jsonschema
  - jupyter-packaging
  - jupyter_client
  - jupyter_core
  - jupyter_server
  - jupyterlab
  - jupyterlab_server
  - kiwisolver
  - libcurl
  - libpng
  - libtiff
  - markupsafe
  - matplotlib-base
  - nbclassic
  - nbclient
  - nbconvert
  - nbformat
  - notebook
  - numpy
  - pillow
  - pip
  - proj
  - python
  - python-dateutil
  - pytz
  - requests
  - scipy
  - shapely
  - six
  - sqlite
  - urllib3
  - xz
  - zeromq
  - zipp
  - zlib
  - zstd
